### ISSUE TITLE
Spx2.0, panic lack of gdspx-windows-amd64.dll

### ISSUE THREAD

**Issue by qlli** [goplus/spx#385]
![image](https://github.com/user-attachments/assets/e62a6a17-6e07-4ca0-a352-4b274e494914)
gdspx\cmd\gdspx\pkg\impl\util.go, line 153
During golang building, lib/gdspx-windows-amd64.dll is not copied as expected.

**Comment by JiepengTan** [comment]
You should use the command `spx` instead of `gdspx`, as `gdspx`cannot run `spx` projects.
```
 spx run .\tutorial\00-Blank\
```
![image](https://github.com/user-attachments/assets/9f929419-70f5-46a7-8551-40c11782117c)
