### ISSUE TITLE
gop run panic in 09-AircraftWar

### ISSUE THREAD

**Issue by damonchen** [goplus/spx#5]
2021/10/01 07:25:29 Member Initialize false // *index
panic: -:  undefined (type *index has no field or method Initialize)

goroutine 1 [running]:
github.com/goplus/gox.(*CodeBuilder).MemberVal(...)
	github.com/goplus/gox@v1.7.7/codebuild.go:1376
github.com/goplus/gop/cl.gmxMainFunc(0xc0029b7d40, 0xc002a0b200)
	github.com/goplus/gop/cl/class_file.go:160 +0x345

The problem is that calling `Initialize` function not exist

**Comment by xushiwei** [comment]
rm $SPXROOT/.gop/cache
